In [3]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


In [6]:
x = np.ones((3,3))
x = np.zeros((8,8), dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
x = np.zeros((5, 5), dtype = int)
x += np.arange(5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [9]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.51538509 0.18250686 0.94765566]
  [0.20008709 0.67115304 0.42004598]
  [0.24151948 0.34938602 0.15361134]]

 [[0.66263716 0.3964921  0.32262747]
  [0.25657879 0.63667437 0.94408256]
  [0.94959856 0.72219786 0.40289251]]

 [[0.97369804 0.43935032 0.69465222]
  [0.37274587 0.42811999 0.47410328]
  [0.1495103  0.57712384 0.25616522]]]


In [11]:
x = np.zeros((5, 5), dtype = int)
x[::, 0::4] = 0
x[0::4, ::] = 1
x[::, 0::4] = 1
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [21]:
x = np.random.randint(10, 40, size = 10, dtype = int)
x.sort()
print(x)

[12 12 14 15 20 22 25 31 31 36]


In [28]:
x = np.arange(25).reshape(5, 5)
print(x.size)
print(x.shape)

25
(5, 5)


In [7]:
import pandas as pd

a = pd.Series([1, 2, 3, 4])
b = pd.Series([5, 6, 7, 8])
sum((a - b)**2)**(1/2)

8.0

In [16]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'
dataframe = pd.read_csv(url)
dataframe.head(3)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1

In [12]:
dataframe.tail(2)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

In [13]:
dataframe.shape

(539383, 8)

In [14]:
dataframe.describe()

Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [15]:
dataframe.iloc[1:4]

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1

In [21]:
dataframe[dataframe['DayOfWeek'] == 3].head(10)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0
7      DL    2722         PHX       DTW          3    30     228      0
8      DL    2606         SFO       MSP          3    35     216      1
9      AA    2538         LAS       ORD          3    40     200      1

In [28]:
import numpy as np
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)

feature = np.array([[-500], [-100], [0], [100], [900]])
scaler = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = scaler.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])