<a href="https://colab.research.google.com/github/BigSekas/WB_mirea/blob/main/Workbook2_Mironov_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Пример 1.2.1**

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


**Пример 1.2.2**

Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19

In [ ]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


**Пример 1.2.3**

Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [ ]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0020544735804036707 0.9860477256492455 0.513597029561748


**Пример 1.2.4**

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [ ]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**Пример 1.2.5**

Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


**Пример 1.2.6**

Отсортировать массив.

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


**Задание 1.3.1**

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
x = np.ones((3,3))
x = np.zeros((8,8), dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Задание 1.3.2**

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
x = np.zeros((5, 5), dtype = int)
x += np.arange(5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**Задание 1.3.3**

Создать массив 3x3x3 со случайными значениями.

In [ ]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.99856733 0.56348318 0.7459275 ]
  [0.23478753 0.90217797 0.54111528]
  [0.36499267 0.84752133 0.69131012]]

 [[0.9505183  0.47892883 0.60567126]
  [0.82046083 0.21773374 0.14683185]
  [0.10339884 0.82558137 0.2113447 ]]

 [[0.74729578 0.4464722  0.45487721]
  [0.72490273 0.29430612 0.90429318]
  [0.80875526 0.17720168 0.56006517]]]


**Задание 1.3.4**

Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
x = np.zeros((5, 5), dtype = int)
x[::, 0::4] = 0
x[0::4, ::] = 1
x[::, 0::4] = 1
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Задание 1.3.5**

Создайте массив и отсортируйте его по убыванию.

In [ ]:
Z = np.array([0, 5, 7, 4, 17, 9, -5, 8])
Z = np.sort(Z)
print(Z[::-1])

[17  9  8  7  5  4  0 -5]


**Задание 1.3.6**

Создайте матрицу, выведите ее форму, размер и размерность.


In [ ]:
Z = np.array([[10, -5, 15], [30, -6, 91]])
if (Z.shape[0]==Z.shape[1]):
    print("Матрица квадратная")
else:
    print("Матрица прямоугольная")
print(f"Размер матрицы: {Z.size}")
print(f"Размерность матрицы: {Z.shape}")

Матрица прямоугольная
Размер матрицы: 6
Размерность матрицы: (2, 3)


**Пример 2.2.1**

Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [ ]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


**Пример 2.2.2**

Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


**Пример 2.2.3**

Создайте новый фрейм данных.


In [ ]:
dataframe =pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

**Пример 2.2.4**

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

PS. Фрейм более не доступен.

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'
dataframe = pd.read_csv(url)
dataframe.head(3)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1

**Пример 2.2.5**

Пронализировать характеристики фрейма данных.


In [ ]:
dataframe.head(2)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1

In [ ]:
dataframe.tail(3)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

In [ ]:
dataframe.shape

(539383, 8)

In [ ]:
dataframe.describe()

Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

**Пример 2.2.6**

Выберите индивидуальные данные или срезы фрейма данных.


In [ ]:
dataframe.iloc[1:4]

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1

**Пример 2.2.7**

Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [ ]:
dataframe[dataframe['DayOfWeek'] == 3].head(10)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0
7      DL    2722         PHX       DTW          3    30     228      0
8      DL    2606         SFO       MSP          3    35     216      1
9      AA    2538         LAS       ORD          3    40     200      1

**Задание 2.3.1**

Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [ ]:
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])

print(sum((a-b)**2)**.5)

2.0


**Задание 2.3.2**

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
dataframe

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer
6    True     steep      high  chapparal

**И Т.Д. уитывая что ссылка из примера более недоступна, я изначально выбрал другой фрейм.**

**Пример 3.2.1**

Прошкалируйте числовой признак в диапазон между двумя значениями.


In [ ]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

#Созать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Созать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

#Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

**Пример 3.2.2**

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Созать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [ ]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


**Пример 3.2.3**

Дан фрейм данных
```
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})
 ```
Необходимо масштабировать его числовые столбцы.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest  = pd.DataFrame({
'slope 1':[14.00,90.20,90.95,96.27,91.21],
'slope 2':[103.02,107.26,110.35,114.23,114.68],
'slope 3':['big','small','big','small','small']
})
dfTest[['slope 1', 'slope 2']] = scaler.fit_transform(dfTest[['slope 1', 'slope 2']])
dfTest

slope 1   slope 2 slope 3
0  0.000000  0.000000     big
1  0.926219  0.363636   small
2  0.935335  0.628645     big
3  1.000000  0.961407   small
4  0.938495  1.000000   small

**Задание 3.3.2**

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
from sklearn.preprocessing import StandardScaler

dframe = pd.read_csv(r'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
scaler = MinMaxScaler()
dframe[['sepal_length_cm']] = scaler.fit_transform(dframe[['sepal_length_cm']])
scaler = StandardScaler()
dframe[['sepal_width_cm']] = scaler.fit_transform(dframe[['sepal_width_cm']])
dframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]